version: "3"
services:
    web:
        image: dancook993/test:nginx
        build:
            context: ./nginx-server
            dockerfile: Dockerfile
        ports:
              - 8090:80
    jenkins:
        image: dancook993/test:jenkins
        build:
            context: ./jenkins-server
            dockerfile: Dockerfile
        depends_on:
            - "web"